services:
  ntp:
    build:
      context: ./ntp
      dockerfile: Dockerfile
    image: local/chrony:alpine-3.20
    container_name: ntp-server
    restart: unless-stopped
    ports:
      - "123:123/udp"
      - "323:323/udp"
    volumes:
      - ./ntp/chrony.conf:/etc/chrony/chrony.conf:ro
      - chrony-data:/var/lib/chrony
    cap_add:
      - SYS_TIME
    healthcheck:
      test: ["CMD-SHELL", "chronyc -n tracking >/dev/null 2>&1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  healthcheck:
    build: ./healthcheck
    image: local/ntp-health:alpine-3.20
    container_name: ntp-healthcheck
    restart: unless-stopped
    ports:
      - "8123:80"
    depends_on:
      - ntp
    environment:
      - NTP_TARGET=ntp
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/status.txt | grep -Eq 'Leap status *: Normal|ERREUR'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

volumes:
  chrony-data:
